#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - yarn
              - yarn build
#        - step:
#            name: Code linting
#            script:
#              - npm install eslint
#              - npx eslint .
#            caches:
#              - node
    - step:
        name: Deploy
        script:
          - pipe: atlassian/ssh-run:0.8.1
            variables:
              SSH_USER: 'photon-roami-bot'
              SERVER: '134.122.3.91'
              COMMAND: 'pwd'